### ISSUE TITLE
DRDynamicSlideShow gone?

### ISSUE THREAD

**Issue by djclarkson** [Dromaguirre/Popsicle#12]
Hey there, I'm new to IOS so please forgive this likely very noob question.

I have an IOS project that was using DRDynamicSlideShow. When I go now to pod update I get an error saying: 

warning: Could not find remote branch 1.0.1 to clone. fatal: Remote branch 1.0.1 not found in upstream origin

All links to that Pod took me to the Popsicle repo. So I tried adding Popsicle to the project instead but that doesn't work.

Once again sorry for noob question.

**Comment by Dromaguirre** [comment]
Hey there @djclarkson.

It's a not a noob question at all.

You should be able to replace DRDynamicSlideShow's pod with Popsicle's by replacing this line from your Podfile:

```ruby
pod 'DRDynamicSlideShow'
```

to this one:

```ruby
pod 'Popsicle'
```

and running `pod install` or `pod update` as convenient.

If you're still having trouble, please tell me what error you're getting from CocoaPods.

Another solution I can think of right now is removing `pod 'DRDynamicSlideShow'` from your Podfile, running `pod install` to remove it from your project, and adding `pod 'Popsicle'` afterwards.

**Comment by djclarkson** [comment]
Ok so I tried removing DRDynamicSlideshow then pod install, then adding Popsicle. On build I get this:

Property ‘DRDynamicSlideShowdelegate’ not found on object of type ‘RMDateSelectionViewController'

**Comment by Dromaguirre** [comment]
That's because Popsicle is a hole different thing than DRDynamicSlideShow. Please consider the new API and implement it as convenient for your project. I'd recommend implementing DRPageScrollView (check out the demo app for further detail on implementation).

**Comment by djclarkson** [comment]
I figured it was a whole different thing but then the suggestion you made above was to simply replace the Pods. Is there no way to keep the old repository available? Kind of sucks for projects to break like this and be forced to re-implement (I'm not experience enough to do so myself, so probably have to pay....).

**Comment by Dromaguirre** [comment]
I'm really sorry, but there's no way around it. I should have deprecated the previous project instead of replacing it for this one. My mistake. If you still have the old library files, you can upload them to your own private repository and install them from there though. Or maybe you could install manually, since there won't be more updates for the library for CocoaPods to manage.

**Comment by djclarkson** [comment]
It's ok, I will see if I can find the old files.

**Comment by Dromaguirre** [comment]
:+1:

**Comment by djclarkson** [comment]
Wow this is a hell of a lot more work to resolve than I thought. Do you have a copy of the old repository I can use? I have a few files but had trashed the old cloned directory.

**Comment by Dromaguirre** [comment]
Unfortunately I don't, sorry.

I'm quite certain it shouldn't be hard at all to port your code to Popsicle+DRPageScrollView. It's quite the same thing as DRDynamicSlideShow except for the method names.

**Comment by Dromaguirre** [comment]
Hi again @djclarkson.

How stupid from me not to think about this before: a lot of people have a forked version of the old repository, such as [__this one__](https://github.com/lunayo/DRDynamicSlideShow).
