### ISSUE TITLE
Remove old pod from cocoapods

### ISSUE THREAD

**Issue by AndrewDryga** [Dromaguirre/Popsicle#14]
Hi,

We want to replace it with our fork, since you dropped iOS 7 support, renamed repo and force pushed all the code. Don't do that again.

https://cocoapods.org/pods/DRDynamicSlideShow

**Comment by Dromaguirre** [comment]
Hi.

I'm really sorry about that. I shouldn't have done it that way in the first place.

How should I do it to remove the pod? I think it's impossible through trunk.

**Comment by AndrewDryga** [comment]
Is it possible to rename it?

**Comment by Dromaguirre** [comment]
From what I've seen, it's impossible to actually remove a podspec. But don't worry, there's a pretty clean solution.

You can set up a private spec repository and add DRDynamicSlideShow to it as a private podspec linked to your forked version. [__Check this out__](https://guides.cocoapods.org/making/private-cocoapods.html) for more info about private podspecs. I've tried it myself and it's fairly easy to set up.

Again, sorry for the inconveniences.
